- name: Get local dir
  local_action: shell pwd
  register: result
- name: Copy sources
  synchronize:
    src: "{{result.stdout}}/{{rdma_core_src_source}}"
    dest: "{{rdma_core_src_destination}}"
    delete: true
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=.config"
      - "--exclude=*.pb.go"
      - "--exclude=*.o"
      - "--exclude=*.d"
      - "--filter=:- .gitignore"
