---
- name: Install all required dev packages
  become: true
  apt:
    update_cache: true
    pkg:
      - libnl-route-3-dev
      - pandoc
      - docutils-common
      - iproute2
      - libmnl-dev
      - libnl-genl-3-dev
      - cmake
      - pkg-config
      - libtool
      - libudev-dev
      - libsystemd-dev
      - libdrm-dev
- include_tasks: github.yaml
  when: 'rdma_core_fetch_method == "github"'
- include_tasks: git_rsync.yaml
  when: 'rdma_core_fetch_method == "git_rsync"'
- include_tasks: git_push.yaml
  when: 'rdma_core_fetch_method == "git_push"'
- name: Configure rdma-core
  shell: |
    cmake -D CMAKE_INSTALL_PREFIX={{rdma_core_install_destination}} \
      -DCMAKE_INSTALL_RPATH={{rdma_core_install_destination}}/lib \
      -DCMAKE_BUILD_TYPE={{rdma_core_build}} \
      {{rdma_core_cmake_flags}} \
      -S . -B build
  args:
    chdir: "{{ rdma_core_src_destination }}"
    creates: "{{ rdma_core_src_destination }}/build/Makefile"
- name: Compile rdma-core
  make:
    chdir: "{{ rdma_core_src_destination }}/build"
  register: rdma_core_compile
- name: Install rdma-core
  become: "{{rdma_core_install_become}}"
  shell: |
    cmake --install build
  args:
    chdir: "{{ rdma_core_src_destination }}"
  when: rdma_core_compile.changed
